#!/bin/bash
C:/Python27/python.exe ./sxd2017.com/download.py &
C:/Python27/python.exe ./pawoo.net/download.py &
C:/Python27/python.exe ./mastodon.cloud/download.py &
C:/Python27/python.exe ./mastodon.xyz/download.py &
C:/Python27/python.exe ./octodon.social/download.py &
C:/Python27/python.exe ./mamot.fr/download.py &
C:/Python27/python.exe ./music.pawoo.net/download.py &
C:/Python27/python.exe ./social.tchncs.de/download.py &
C:/Python27/python.exe ./mimumedon.com/download.py &
C:/Python27/python.exe ./mao.daizhige.org/download.py &
C:/Python27/python.exe ./mstdn.io/download.py &
C:/Python27/python.exe ./mastodon.technology/download.py &
C:/Python27/python.exe ./lou.lt/download.py &
C:/Python27/python.exe ./social.lou.lt/download.py &
C:/Python27/python.exe ./mstdn18.jp/download.py &
C:/Python27/python.exe ./framapiaf.org/download.py &
C:/Python27/python.exe ./mastodon.host/download.py &
C:/Python27/python.exe ./noagendasocial.com/download.py &
C:/Python27/python.exe ./kirakiratter.com/download.py &
C:/Python27/python.exe ./mstdn-workers.com/download.py &
C:/Python27/python.exe ./hex.bz/download.py &
C:/Python27/python.exe ./mastodon.blue/download.py &
C:/Python27/python.exe ./otajodon.com/download.py &
C:/Python27/python.exe ./ro-mastodon.puyo.jp/download.py &
C:/Python27/python.exe ./imastodon.net/download.py &
C:/Python27/python.exe ./mastodon.rocks/download.py &
C:/Python27/python.exe ./hearthtodon.com/download.py &
C:/Python27/python.exe ./mastodon.at/download.py &
C:/Python27/python.exe ./mathtod.online/download.py &
C:/Python27/python.exe ./mstdn.tokyocameraclub.com/download.py &
C:/Python27/python.exe ./mastodon.club/download.py &
C:/Python27/python.exe ./vocalodon.net/download.py &
C:/Python27/python.exe ./oc.todon.fr/download.py &
C:/Python27/python.exe ./mastodon.nara.jp/download.py &
C:/Python27/python.exe ./cmx.im/download.py &
C:/Python27/python.exe ./hostux.social/download.py &
C:/Python27/python.exe ./niu.moe/download.py &
C:/Python27/python.exe ./masto.themimitoof.fr/download.py &
C:/Python27/python.exe ./awoo.space/download.py &
C:/Python27/python.exe ./mastodon.yokohama/download.py &
C:/Python27/python.exe ./mastodon.fun/download.py &
C:/Python27/python.exe ./ffxiv-mastodon.com/download.py &
C:/Python27/python.exe ./mastodon.cc/download.py &
C:/Python27/python.exe ./mstdn.kemono-friends.info/download.py &
C:/Python27/python.exe ./mastodon.zaclys.com/download.py &
C:/Python27/python.exe ./mstdn.osaka/download.py &
C:/Python27/python.exe ./dhtls.net/download.py &
C:/Python27/python.exe ./ichiji.social/download.py &
C:/Python27/python.exe ./matchdon.com/download.py &
C:/Python27/python.exe ./mastodon.art/download.py &
C:/Python27/python.exe ./otoya.space/download.py &
C:/Python27/python.exe ./mastodon.juggler.jp/download.py &
C:/Python27/python.exe ./mastodon.gougere.fr/download.py &
C:/Python27/python.exe ./ika.queloud.net/download.py &
C:/Python27/python.exe ./tuner.1242.com/download.py &
C:/Python27/python.exe ./3.nu/download.py &
C:/Python27/python.exe ./soc.ialis.me/download.py &
C:/Python27/python.exe ./gamecreate.mstdn.cloud/download.py &
C:/Python27/python.exe ./mastodon.top/download.py &
C:/Python27/python.exe ./photodn.net/download.py &
C:/Python27/python.exe ./eigadon.net/download.py &
C:/Python27/python.exe ./chaos.social/download.py &
C:/Python27/python.exe ./social.nasqueron.org/download.py &
C:/Python27/python.exe ./tablegame.mstdn.cloud/download.py &
C:/Python27/python.exe ./unixcorn.xyz/download.py &
C:/Python27/python.exe ./aidon.club/download.py &
C:/Python27/python.exe ./mathstodon.xyz/download.py &
C:/Python27/python.exe ./natudon-outdoor.net/download.py &
C:/Python27/python.exe ./mstdn.hokkaido.jp/download.py &
C:/Python27/python.exe ./gbtdn.tokyo/download.py &
C:/Python27/python.exe ./mastodon.sdf.org/download.py &
C:/Python27/python.exe ./m6n.jp/download.py 
